# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0004_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='battery_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='light_data',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='x_coord',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='y_coord',
            field=models.FloatField(null=True),
        ),
    ]
