# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0005_auto_20171024_0136'),
        ('demosky', '0005_auto_20171023_2325'),
    ]

    operations = [
    ]
