# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0008_auto_20171112_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensormine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensornumber', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField()),
                ('chargestate', models.FloatField(null=True)),
                ('lightint', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensornumber',
            field=models.IntegerField(null=True),
        ),
    ]
