# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0014_auto_20171201_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
