# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0016_auto_20171201_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='add_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensors',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
