# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0017_auto_20171201_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
